### ISSUE TITLE
Packaged, Connected to Server, Now It doesnt upload anything

### ISSUE THREAD

**Issue by logro16** [rezanid/azureuploader#4]
Im trying to figure out what I did wrong, built the solution, imported it, and connected to Azure Blob, I can attach a file, it goes to 0% then after a few minutes just reset. @rezanid, Any help would be appreciated.

**Comment by rezanid** [comment]
If you think everything is setup correctly, you can try opening Developer toolbox of your browser and look at the network tab. See what happens when you pick a new file in the browser. Do you see any new request being sent to your storage account? Do any requests fail?
